### ISSUE TITLE
[bug] Could not find a declaration file for module @ensdomains/thorin 

### ISSUE THREAD

**Issue by yussdev** [ensdomains/thorin#137]
### Package Version

0.6.44

### Current Behavior

There are no types for the package 
![image](https://github.com/ensdomains/thorin/assets/51474231/c9771f71-cea4-425f-a4c1-5991254fcc8f)

**Comment by gskril** [comment]
This makes sense if you were unable to install Thorin. Please try installing with the `--legacy-peer-deps` flag I suggested in #136
